### ISSUE TITLE
RadioRxTimeout for unconfirmed messages

### ISSUE THREAD

**Issue by darkfader** [Lora-net/LoRaMac-node#864]
This happens sometimes and I don't know why.
MacCtx.MacFlags.Bits.McpsReq is set and it keeps retransmitting endlessly. Since it's an unconfirmed message (ChirpStack says that, don't know if that can be trusted) and got a MIC error, it won't get a response. (the devaddr and skeys seem to be updated)
It would help as workaround if it gives up after a while.
I'm using latest develop branch.

Stack-trace:
```
#0  0x00007150 in HandleRadioRxErrorTimeout (
    rx1EventInfoStatus=rx1EventInfoStatus@entry=LORAMAC_EVENT_INFO_STATUS_RX1_TIMEOUT,
    rx2EventInfoStatus=rx2EventInfoStatus@entry=LORAMAC_EVENT_INFO_STATUS_RX2_TIMEOUT)
    at ../semtech-loramac/src/mac/LoRaMac.c:1408
#1  0x0000851c in ProcessRadioRxTimeout ()
    at ../semtech-loramac/src/mac/LoRaMac.c:1450
#2  LoRaMacHandleIrqEvents () at ../semtech-loramac/src/mac/LoRaMac.c:1450
#3  LoRaMacProcess () at ../semtech-loramac/src/mac/LoRaMac.c:1662
#4  0x0000fcc6 in LmHandlerProcess ()
    at common/semtech-loramac/src/apps/LoRaMac/common/LmHandler/LmHandler.c:381
#5  0x00005a50 in task_run () at common/os/task.c:83
#6  0x00004060 in system_run () at common/lib/lib.c:82
#7  0x00002426 in main () at ./main.c:183
```

I think it happens at/after the clock synchronisation.

Added some printf:
```
[  11.638] IsClockSynched 1
[  11.642] 
[  11.642] ###### =========== MCPS-Request ============ ######
[  11.642] ######           MCPS_UNCONFIRMED            ######
[  11.642] ###### ===================================== ######
[  11.642] STATUS      : OK
[  12.967] MacCtx.MacCallbacks->MacProcessNotify
[  12.967] events.Events.RxTimeout
[  12.968] LoRaMacHandleMlmeRequest: resetting NbTransCounter
[  12.968] Arrange further retransmission
[  14.295] MacCtx.MacCallbacks->MacProcessNotify
[  14.295] events.Events.RxTimeout
[  14.295] LoRaMacHandleMlmeRequest: resetting NbTransCounter
[  14.295] Arrange further retransmission
...
[  30.228] events.Events.RxTimeout
[  30.228] LoRaMacHandleMlmeRequest: resetting NbTransCounter
[  30.228] Arrange further retransmission
[  31.555] MacCtx.MacCallbacks->MacProcessNotify
[  31.555] events.Events.RxTimeout
[  31.556] LoRaMacHandleMlmeRequest: resetting NbTransCounter
[  31.556] Arrange further retransmission
[  32.883] MacCtx.MacCallbacks->MacProcessNotify
[  32.883] events.Events.RxTimeout
[  32.883] LoRaMacHandleMlmeRequest: resetting NbTransCounter
[  32.883] Arrange further retransmission
[  34.211] MacCtx.MacCallbacks->MacProcessNotify
[  34.211] events.Events.RxTimeout
[  34.211] LoRaMacHandleMlmeRequest: resetting NbTransCounter
[  34.211] Arrange further retransmission
[  35.539] MacCtx.MacCallbacks->MacProcessNotify
[  35.539] events.Events.RxTimeout
[  35.539] LoRaMacHandleMlmeRequest: resetting NbTransCounter
[  35.539] Arrange further retransmission
[  35.678] [LORA] LmHandlerIsBusy
[  36.866] MacCtx.MacCallbacks->MacProcessNotify
[  36.867] events.Events.RxTimeout
```

For now, I did this:
```
           stopRetransmission = CheckRetransUnconfirmedUplink( );
            if (!MacCtx.NodeAckRequested)  stopRetransmission = true;
```

**Comment by HikoSV** [comment]
I confirm the problem.
It happens to me constantly after the rejoin:  it happens at / after the clock synchronization.
I'm using develop branch (commit on Mar 10  2020)

**Comment by djaeckle** [comment]
Hi all, 

thanks for the report. @darkfader , could you tell me which versions you are using?

@HikoSV could you provide some more information to reproduce this issue? Especially, which rejoin do you perform and when does the clock synchronization happen?

**Comment by djaeckle** [comment]
Any feedback to the issue?

**Comment by mluis1** [comment]
No feedback provided. We decide to close the issue.

In case this issue is still existing please reopen it.
